# Generated by Django 5.2 on 2025-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок статьи", max_length=100, verbose_name="Заголовок статьи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите содержимое статьи", null=True, verbose_name="Содержимое статьи"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="photos/",
                        verbose_name="Превью(изображение)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату создания статьи",
                        verbose_name="Дата создания статьи",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Отметьте для публикации статьи", verbose_name="Признак публикации"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["title"],
            },
        ),
    ]
